In [47]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam (1).csv

In [48]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk #text aur language ko computer se analyze
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
df = pd.read_csv('spam.csv',encoding='latin-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [49]:
df=df.drop(['Unnamed: 2', 'Unnamed: 3','Unnamed: 4'],axis=1)#Rows
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [50]:
# Renaming v1 & v2 as Category & Text
df=df.rename(columns={"v1":"Category","v2":"Text"})
#Sample post modifications
df.head()

  Category                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [51]:
#Let's check the length of the dataset
print(" Total number of rows in the dataset are", len(df))

 Total number of rows in the dataset are 5572

In [52]:
#Descriptive Summary of the dataset
df.describe()

       Category                    Text
count      5572                    5572
unique        2                    5169
top         ham  Sorry, I'll call later
freq       4825                      30

In [53]:
#Let's create a column to check of each text & plot a histogram to check the distirbution
df['Length']=df['Text'].apply(len)
display(df.head())

  Category                                               Text  Length
0      ham  Go until jurong point, crazy.. Available only ...     111
1      ham                      Ok lar... Joking wif u oni...      29
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3      ham  U dun say so early hor... U c already then say...      49
4      ham  Nah I don't think he goes to usf, he lives aro...      61

In [54]:
#distribution of the data
import plotly.express as px
fig = px.histogram(df, x='Length', marginal='rug',
title='Histogram of Text Length')
fig.update_layout(    xaxis_title='Length',    yaxis_title='Frequency',    showlegend=True)

In [56]:
df.loc[:,'Category']=df.Category.map({'ham':0, 'spam':1})
df['Category'] = df['Category'].astype(int)
df.head()

   Category                                               Text  Length
0         0  Go until jurong point, crazy.. Available only ...     111
1         0                      Ok lar... Joking wif u oni...      29
2         1  Free entry in 2 a wkly comp to win FA Cup fina...     155
3         0  U dun say so early hor... U c already then say...      49
4         0  Nah I don't think he goes to usf, he lives aro...      61

In [58]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
df.shape

(5572, 3)

***CountVectorizer?***

It converts text into a Bag of Words (BoW) representation.

In simple words:It counts how many times each word appears in each message.

In [59]:
count = CountVectorizer()
text = count.fit_transform(df['Text'])
text

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 73916 stored elements and shape (5572, 8672)>

In [60]:
print(text.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [61]:
X=text
Y=df['Category']

In [62]:
#Train & test split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=100)
display('X-Train :', x_train.shape)
display('X-Test :', x_test.shape)
display('Y-Train :', y_train.shape)
display('Y-Test :', y_test.shape)

'X-Train :'

(3900, 8672)

'X-Test :'

(1672, 8672)

'Y-Train :'

(3900,)

'Y-Test :'

(1672,)

***MLPClassifier***

In [63]:
from sklearn.neural_network import MLPClassifier
# This means the neural network has 2 hidden layers:
# First layer → 100 neurons
# Second layer → 50 neurons
mlp_classifier_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000)
mlp_classifier_model.fit(x_train, y_train)
prediction = mlp_classifier_model.predict(x_test)
prediction[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
# Calculate and print classification metrics
print("MLP Classifier")
print("Accuracy score: {:.2f}".format(accuracy_score(y_test, prediction)))
print("Precision score: {:.2f}".format(precision_score(y_test, prediction)))
print("Recall score: {:.2f}".format(recall_score(y_test, prediction)))
print("F1 score: {:.2f}".format(f1_score(y_test, prediction)))

MLP Classifier
Accuracy score: 0.98
Precision score: 0.97
Recall score: 0.89
F1 score: 0.93

**Naive_Bayes**

In [65]:
from sklearn.naive_bayes import MultinomialNB
multinomial_nb_model = MultinomialNB()
multinomial_nb_model.fit(x_train, y_train)  # Train the model
prediction = multinomial_nb_model.predict(x_test)
print("Multinomial NB")
print("Accuracy score: {}". format(accuracy_score(y_test, prediction)) )
print("Precision score: {}". format(precision_score(y_test, prediction)) )
print("Recall score: {}". format(recall_score(y_test, prediction)))
print("F1 score: {}". format(f1_score(y_test, prediction)))

Multinomial NB
Accuracy score: 0.9814593301435407
Precision score: 0.9174311926605505
Recall score: 0.9389671361502347
F1 score: 0.9280742459396751

Bernoulli Naive Bayes model

In [66]:
from sklearn.naive_bayes import BernoulliNB
bernoulli_nb_model = BernoulliNB()
bernoulli_nb_model.fit(x_train, y_train)
prediction = bernoulli_nb_model.predict(x_test)
#Evaluation
print( "Bernoulli NB")
print( "Accuracy score: {:.2f}".format(accuracy_score(y_test, prediction)))
print( "Precision score: {:.2f}".format (precision_score(y_test, prediction)))
print( "Recall score: {:.2f}".format (recall_score(y_test, prediction)))
print( "F1 score: {:.2f}".format (f1_score(y_test, prediction)))

Bernoulli NB
Accuracy score: 0.98
Precision score: 1.00
Recall score: 0.87
F1 score: 0.93

..............